name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: helptag test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      - name: helptag-github-check
        uses: ./
