name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: helptag test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
      - name: helptag-github-check
        uses: ./
