name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: helptag test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: helptag-github-check
        uses: ./
